# Generated by Django 5.2 on 2025-04-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marketoon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='func_registrar_produto',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='func_registrar_produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='func_registrar_produto',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
